title: "Kankakee Community College"
site_name: KCC Startup Template
public-url: "https://www.kcc.edu" ## This gets generated into the link that displays in the footer (the one above the social icons)
url: 'URL is needed for robots.txt to work properly' ## NO TRAILING SLASHES!!/<--nope
theme: "kcc-gem-theme"
google-tag_key: Google Tag Manager key goes here
#translate: true ## Uncomment to activate Google Translate Powers!!
nav_links:
  - link_text: Home
    link_href: ''
    button: false
  - link_text: Landing Page
    link_href: 'landing-page'
    button: false
  - link_text: Accordion
    link_href: accordion
    button: false
#  - link_text: Example External Link
#    link_href: 'https://example-external-link.com'
#    button: false
#    external: true  <---- #### Add the `external: true` key & value to make an external link ####
#
#### Example sub-nav configuration below #### ======================================================= #
##                                                                                                   ##
##   link_href's must have a single '/' in the link (no '/' in the begining or end of the string)    ##
##                                                                                                   ##
## ================================================================================================== #
#
#sub-nav_links:
#  - link_text: Sheets
#    link_href: 'reference/gsheets'
#  - link_text: CloudCannon
#    link_href: 'reference/cloudcannon'
#
collections:
  posts:
    output: false
    _hide_content: true
  contacts:
    output: false
  accordions:
    output: false
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    title: ''
    permalink: /:categories/:title/
    baseurl: ../../../
    categories: news
permalink: pretty
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
# Delete this comment and place description on this line
baseurl: "" # the subpath of your site, e.g. /blog
# include:
#   - "_pages"
#   - "_posts"

# include future posts? (true or false)
future: true
# Build settings
markdown: kramdown

exclude:
  - "gulpfile.js"
  - "gulp-tasks/"
  - "node_modules"
  - "npm-debug.log"
  - "package.json"
  - "package-lock.json"
  - "README.md"
  - "Gemfile"
  - "Gemfile.lock"
  - "gulpconfig.yml"
  - "webpack.config.js"
  - "install.sh"
  - "install_template.sh"
  - "WEBPACK-BABEL-COREJS_INFO.md"
  - "siteicon.png"
  - "page-startups"
  - "UPDATE_PROCEDURE.md"
  - "ruby-version.txt"

uploads_dir: # specifies the default uploads directory for CloudCannon
  - "uploads/"

_comments:
  layout: Do NOT modify layouts. It may break things.
  baseurl: Do NOT modify baseurl. It WILL break all page links.
  categories: "FOR CATEGORIES <br/>SPORTS-SPECIFIC: <br/>1.) First enter the sport's category from this list <br/>2.) followed by the \"news\" category. <br/>(e.g. mens-basketball news) <br/>GENERAL NEWS: <br/>1.) Enter \"news\" category first <br/>2.) followed by the \"general\" category. <br/>(e.g. news general)"
  sport_category: Sport for which news item pertains. Gets pulled into news rollup.
  news_thumb_image: Must be 16:9 ratio image. Preferably 200px wide.
  description: "Descriptions are seen by search engines like Google and displayed in search results"

_options: # The CloudCannon options key
  layout: # We don't want users changing these!!
    hidden: true
  baseurl: # We don't want users changing these!!
    hidden: true
  translate:
    hidden: true # Prevent CloudCannon Users from randomly turning translate on in their site.
