browsersync:
  notify: true
  open:   false # set to true to open localhost:3000 in chrome browser upon execution of gulp command.
  port:   3000
  server:
    basedir: "_site/"
  xip:    false
  browser: "Google Chrome"

clean:
  # The jekyll build dir
  - "_site" # clean these folders on execution of gulp command
#  - "_posts/*"

copy:
  # Paths to static assets that aren't (S)CSS or JavaScript
  # because these are completely handled by the sass and javascript tasks
  # The two comments above this one came from the template.
  # We copy all JS and SCSS because Google Chrome Inspect will tell you where the style is located within the sass structure.
  assets:
    # all files below the assets dir
    # everything gets copied to site build becuase some JS files are linked directly into pages and not compiled into all.min.js)
    - "assets/**/*"
    # exclusions: (Don't copy these items because they are handled by other gulp tasks)
    - "!assets/{js,scss,css}/**/*"   # js, scss and css files
    - "!assets/css{,/**}"            # css dir
    - "!assets/js{,/**}"             # js dir
    - "!assets/scss{,/**}"           # scss dir
  dist: "_site/assets/"
  notification: "Running Copy"

sass:
  # Autoprefixer will make sure your CSS works with these browsers
  compatibility:    # These are pretty standard autoprefixer compatibility settings
    - "last 2 versions"
    - "ie >= 9"
    - "defaults"
  dest:
    jekyllRoot: "assets/css/"
    buildDir: "_site/assets/css/"
  notification: "Running Sass"
  src: "assets/scss/main.scss"

javascript:
  dest:
    jekyllRoot: "assets/js/"
    buildDir: "_site/assets/js/"
  filename: "all.min.js"
  notification: "Running JavaScript"
  src:
    # Exclusions: (!exclaim to exclude)
    # Inclusions: (included in JS compile)
    - "assets/js/test.js" # test js file

sitemap:
  src:
    - "_site/*.html"
    - "_site/**/*.html"
    - "_site/**/**/*.html"
    - "_site/**/*.pdf"
    - "_site/**/**/*.pdf"
  siteUrl:
    - "http://athletics.kcc.edu"

jekyll:
  notification: "Running jekyll"

watch: # 'Watch' for changes in all the following:
  images: "assets/img/**/*"
  javascript:
    - "assets/js/all.min.js"
    - "assets/js/*.js"
  sass: "assets/scss/**/*.scss"
  pages:
    - "*.{md,html,yml,xml}"
    - "{_data,_includes,_layouts,_pages,_posts,_alerts}/**/*.{md,html,yml,xml}"
    # All these subfolders are added because the watch task was not looking deep enough
    # !exlclusions:
    - "!_site/**/*.*"
    - "!assets/**/*.*"
