browsersync:
  notify: true
  open:   false # set to true to open localhost:3000 in chrome browser upon execution of gulp command.
  port:   3000
  server:
    basedir: "_site/"
  xip:    false
  browser: "Google Chrome"

# Clean the jekyll _site/ build dir.
clean:
  - "_site" # clean these folders on execution of gulp command
#  - "_posts/*"

# Copy task coppies static assets like images into site build
# Any changes to Copy task should be also be made to travisCopy.
copy:
  # Paths to static assets that aren't (S)CSS or JavaScript
  # because these are completely handled by the sass and javascript tasks.
  assets:
    - "assets/css/*"
    - "assets/img/*"
    - "assets/js/dist/*"
    # exclusions: (Don't copy these items because they are handled by other gulp tasks)
    - "!assets/{js,scss,css}/**/*"   # js, scss and css files
    - "!assets/css{,/**}"            # css dir
    - "!assets/js{,/**}"             # js dir
    - "!assets/scss{,/**}"           # scss dir
  dist: "_site/assets/"
  notification: "Running Copy"

copyVendor:
  assets:
    # all files below the assets dir
    # everything gets copied to site build becuase some JS files are linked directly into pages and not compiled into all.min.js)
    - "assets/vendor/**/*.*"
  dist: "_site/assets/"
  notification: "Running Copy Vendors"

copyrss:
  assets:
    - "./_site/feed.xml"
  filename:
    - "rss.xml"
  dist:
    - "./"
  notification: "Running Copy RSS"

# Main Gulp Sass task (for main.css).
# Any changes to Sass should be also be made to travisSass.
sass:
  # Autoprefixer will make sure your CSS works with these browsers
  compatibility:    # These are pretty standard autoprefixer compatibility settings
    - "last 2 versions"
    - "ie >= 9"
    - "defaults"
  dest:
    jekyllRoot: "assets/css/"
    buildDir: "_site/assets/css/"
  notification: "Running Sass"
  src: "assets/scss/main.scss"

# Gulp task to create stylesheet for custom CloudCannon editor styles (CMS customizations)
# Any changes to contentSass should be also be made to travisContentSass.
contentSass:
  # Autoprefixer will make sure your CSS works with these browsers
  compatibility:    # These are pretty standard autoprefixer compatibility settings
    - "last 2 versions"
    - "ie >= 9"
    - "defaults"
  dest:
    jekyllRoot: "assets/css/"
    buildDir: "_site/assets/css/"
  notification: "Running contentSass"
  src: "assets/scss/content.scss"

# Gulp task to create sitemap on production builds (`$ gulp --production`).
# Any changes to sitemap task should be also be made to travisSitemap.
sitemap:
  src:
    - "_site/*.html"
    - "_site/**/*.html"
    - "_site/**/**/*.html"
    - "_site/**/*.pdf"
    - "_site/**/**/*.pdf"
  notification: "Running sitemap"
  siteUrl: "styleguide.kcc.edu"

jekyll:
  notification: "Running jekyll"

watch: # 'Watch' for changes in all the following:
  images:
    - "assets/img/**/*"
    - "_data/*.yml"
  sass: "assets/scss/**/*.scss"
  contentSass: "assets/scss/**/*.scss"
  watchWebpack:
    - "assets/js/dist/*.js"
    - "_data/*.yml"
  pages:
    - "*.{md,html,yml,xml}"
    - "{_data,_includes,_layouts,_pages,_posts,_alerts}/**/*.{md,html,yml,xml}"
    # All these subfolders are added because the watch task was not looking deep enough
    # !exlclusions:
    - "!_site/**/*.*"
    - "!assets/**/*.*"
  notification: "Running watch"
